name: anoma-explorer-indexer
contracts:
  - name: ProtocolAdapter
    handler: src/EventHandlers.ts
    events:
      - event: "TransactionExecuted(bytes32[] tags, bytes32[] logicRefs)"
      - event: "ActionExecuted(bytes32 actionTreeRoot, uint256 actionTagCount)"
      - event: "ForwarderCallExecuted(address indexed untrustedForwarder, bytes input, bytes output)"
      - event: "ResourcePayload(bytes32 indexed tag, uint256 index, bytes blob)"
      - event: "DiscoveryPayload(bytes32 indexed tag, uint256 index, bytes blob)"
      - event: "ExternalPayload(bytes32 indexed tag, uint256 index, bytes blob)"
      - event: "ApplicationPayload(bytes32 indexed tag, uint256 index, bytes blob)"
      - event: "CommitmentTreeRootAdded(bytes32 root)"
field_selection:
  transaction_fields:
    - "hash"
networks:
  - id: 42161
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x212f275c6dd4829cd84abdf767b0df4a9cb9ef60"
  - id: 1
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0xdd4f4f0875da48ef6d8f32acb890ec81f435ff3a"
  - id: 11155111
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x2E539c08414DCaBF06305d4095e11096F3d7e612"
  - id: 84532
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x9ED43C229480659bF6B6607C46d7B96c6D760cBB"
  - id: 8453
    start_block: 0
    contracts:
    - name: ProtocolAdapter
      address:
        - "0x9ED43C229480659bF6B6607C46d7B96c6D760cBB"
unordered_multichain_mode: true
